version: '3.2'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    env_file:
      - variables.env

networks:
  default:
    name: nginx-proxy
    external: true